---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "asciinema.fullname" . }}-nginx-config
  labels:
    app: {{ template "asciinema.name" . }}
    chart: {{ template "asciinema.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.conf: |-
    upstream phoenix-server {
        server localhost:4000 fail_timeout=0;
    }

    proxy_cache_path /cache levels=1:2 keys_zone=png_cache:10m max_size=10g
                        inactive=14d use_temp_path=off;

    map $http_x_forwarded_proto $real_scheme {
        default $http_x_forwarded_proto;
        ''      $scheme;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        ### Uncomment this section for HTTPS, replacing <my-cert> as appropriate:
        # listen 443 ssl;
        # ssl_certificate     /app/priv/certs/<my-cert>.crt;
        # ssl_certificate_key /app/priv/certs/<my-cert>.key;

        server_name _;

        root /opt/app/lib/asciinema-0.0.1/priv/static;

        client_max_body_size 16m;

        location / {
            try_files $uri $uri/index.html $uri.html @phoenix;
        }

        # enable caching of PNG previews
        location ~ ^/a/[^.]+\.png$ {
            proxy_cache png_cache;
            proxy_cache_revalidate on;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            proxy_cache_lock on;
            proxy_cache_key $uri;
            proxy_ignore_headers Set-Cookie;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $real_scheme;
            proxy_set_header Host $http_host;
            proxy_pass http://phoenix-server;
            proxy_redirect off;
        }

        # enable caching of digested assets for up to 1 year
        location ~ "^/(css|js|fonts|images)/.+-[0-9a-f]{32}\." {
            expires max;
            add_header Cache-Control public;
            add_header ETag "";
            try_files $uri @phoenix;
        }

        location @phoenix {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $real_scheme;
            proxy_set_header Host $http_host;
            proxy_pass http://phoenix-server;
            proxy_redirect off;
        }
    }

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_types text/plain text/css application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript application/json;
